config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "users#home"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end
end

app/models/add_devise_to_user.rb
class AddDeviseToUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# The `ApplicationRecord` serves as the base class for all models
# in the application. It extends `ActiveRecord::Base` and is used
# to define common configurations or behaviors for models.
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'
  after_save :increment_comments_count

  private

  def increment_comments_count
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'
  after_save :increment_likes_counter

  private

  def increment_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validate :title_not_exceed_250_chars
  validate :comments_counter_greater_than_zero
  validate :likes_counter_greater_than_zero

  belongs_to :author, class_name: 'User'
  has_many :likes, foreign_key: 'post_id', dependent: :destroy
  has_many :comments, foreign_key: 'post_id', dependent: :destroy
  after_save :increment_posts_count

  def most_recent_five_comments
    comments.order(created_at: :desc).limit(5)
  end

  def title_not_exceed_250_chars
    return unless title.present? && title.length > 250

    errors.add(:title, 'cannot exceed 250 characters')
  end

  def comments_counter_greater_than_zero
    return unless comments_counter.present? && comments_counter.negative?

    errors.add(:comments_counter, 'must be greater than or equal 0')
  end

  def likes_counter_greater_than_zero
    return unless likes_counter.present? && likes_counter.negative?

    errors.add(:likes_counter, 'must be greater than or equal 0')
  end

  private

  def increment_posts_count
    author.increment!(:postsCounter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  validates :name, presence: true
  validate :posts_counter_greater_than_zero

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  def most_recent_three_posts
    posts.order(created_at: :desc).limit(3)
  end

  def posts_counter_greater_than_zero
    return unless postsCounter.present? && postsCounter.negative?

    errors.add(:postsCounter, 'must be greater than or equal 0')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name photo bio])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name photo bio])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post_and_user, only: %i[new create]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = @post

    p @comment

    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created.'
    else
      render :new, alert: 'Comment was not created.'
    end
  end

  def set_post_and_user
    @post = Post.find(params[:post_id])
    @user = User.find(params[:user_id])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = Like.new
    @post = Post.find(params[:post_id])
    @like.post = @post
    @like.author = current_user

    if @like.save
      redirect_back(fallback_location: root_path, notice: 'Like was successfully created.')
    else
      render :new, alert: 'Like was not created.'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show]
  before_action :set_user, only: %i[index show new]

  def index
    @posts = @users.posts.includes(:comments)
  end

  def show
    @comments = @posts.comments.includes(:author)
  end

  def new
    @posts = Post.new
  end

  def create
    @posts = Post.new(post_params)
    @posts.author = current_user

    if @posts.save
      redirect_to user_posts_path(current_user, @posts), notice: 'Post was successfully created'
    else
      render :new, alert: 'post was not created.'
    end
  end

  def set_user
    @users = User.find(params[:user_id])
  end

  def set_post
    @posts = Post.includes(:comments).find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/posts_controllers.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  def index
    @posts = Post.all
  end

  def show; end

  def set_post
    @posts = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:home]
  before_action :set_user, only: [:show]

  def home; end

  def index
    @users = User.all
  end

  def show; end

  def set_user
    @users = User.includes(:posts).find(params[:id])
  end
end

app/controllers/users_controllers.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def show; end

  def set_user
    @users = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
# The `ApplicationHelper` module contains methods that can be used
# across the entire application. These helper methods provide common
# functionalities and utilities that can be shared across views
# and controllers.
module ApplicationHelper
end

app/views/comments/new.html.erb
<%= content_for :title, 'Add new comment | ' %>

<h1 class='form_title'>New comment</h1>

<%= render 'shared/form', model: @comment, url: user_post_comments_path, fields: [:text] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <%= render "shared/navbar" %>
    </header>
    <%= render "shared/popup" %>
    <main class='main'>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/index.html.erb
<%= content_for :title, "Posts | " %>

<%= render 'shared/user_card', user: @users, user_card_class: 'user_card no_hover' %>

<div class='post_actions'>
  <%= render 'shared/button', btnName: 'New post +', btnClass: 'btn btn_cta btn_cta_new', btnPath: new_user_post_path(@users) %>
</div>

<ul class='post_list'>
  <% if @posts.empty? %>
    <p class='user_empty-message'>No posts yet!</p>
  <% else %>
    <% @posts.order(created_at: :desc).each do |post| %>
      <li class='post_list_item'>
        <%= render 'shared/post_card', post: post, post_card_class:'post_card post_card_full' %>
        <ul class='comment_list'>
          <% if post.most_recent_five_comments.empty? %>
            <p class='comment_empty-message'>No comments yet!</p>
          <% else %>
            <% post.comments.each do |comment| %>
              <li class='comment_list_item'>
                <%= render 'shared/comment_card', comment: comment %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/posts/new.html.erb
<%= content_for :title, 'Add new post | ' %>

<h1 class='form_title'>New post</h1>

<%= render 'shared/form', model: @posts, url: user_posts_path(@users), fields: [:title, :text] %>

app/views/posts/show.html.erb
<%= content_for :title, "#{truncate(@posts.title.capitalize, length: 20)} | " %>

<div class='post_actions-p'>
  <%= render 'shared/button', btnName: 'New post +', btnClass: 'btn btn_cta btn_cta_new', btnPath: new_user_post_path(@users) %>
</div>

<div class='post_details'>
  <div class='post_details_header'>
    <h1>
      <%= link_to @posts.title.capitalize, user_post_path(@users, @posts), class: 'post_details_title' %>
      <span>by <%= link_to @users.name, user_path(@users), class: 'post_details_header_author' %></span>
    </h1>
    <p class='post_card_counters'>Comments: <%= @posts.comments_counter %> | Likes: <%= @posts.likes_counter %></p>
  </div>

  <p class='post_details_text'><%= @posts.text %></p>

  <div class='post_details_actions'>
    <%= render 'shared/button', btnName: 'Add comment', btnPath: new_user_post_comment_path(@users, @posts), btnClass: 'btn btn_interact' %>
    <%= render 'shared/form', model: @like, url: user_post_likes_path(@users, @posts), fields: [] %>
  </div>
</div>

<ul class='comment_list'>
  <% if @comments.empty? %>
    <p class='comment_empty-message'>No comments yet!</p>
  <% else %>
    <% @comments.includes([:author]).each do |comment| %>
      <li class='comment_list_item'>
        <%= render 'shared/comment_card', comment: comment %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/shared/_button.html.erb
<%= link_to btnName, btnPath, class: btnClass %>

app/views/shared/_comment_card.html.erb
<div class='post_comment_card'>
    <div class='post_comment_author'>
        <p><%= comment.author.name %></p>
    </div>
    <div class='post_comment_text'>
        <p><%= comment.text %></p>
    </div>
</div>

<%= javascript_tag do %>
    function replaceWithDefaultImage(image, default_image_path) {
      image.onerror = "";
      image.src = default_image_path;
      return true;
    }
  <% end %>

  <div class='comment_card'>
    <div class='comment_photo'>
      <%= link_to comment.author do %>
        <% end %>
    </div>

    <div class='comment_text'>
      <p><%= link_to comment.author.name, user_path(comment.author), class: 'comment_author' %></p>
      <p><%= comment.text %></p>
    </div>
  </div>

app/views/shared/_form.html.erb
<%= form_with model: model, url: url, class: 'form', local: true do |f| %>
  <% if model == @like %>
    <%= f.submit 'Like', class: 'btn btn_interact like_btn'%>
  <% else %>
    <% fields.each do |field| %>
      <div class="field">
        <% case field.to_s %>
          <% when 'text' %>
            <%= f.text_area field, placeholder: field.to_s.humanize %>
          <% else %>
            <%= f.text_field field, placeholder: field.to_s.humanize %>
        <% end %>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit class: 'btn btn_cta btn_cta_new' %>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<%= javascript_tag do %>

  function replaceWithDefaultImage(image, default_image_path) {

    image.onerror = "";

    image.src = default_image_path;

    return true;

  }

<% end %>




<nav class="nav">

  <%= link_to "Troos App", root_path, class: "nav_logo" %>




  <ul class="nav_links">

    <% if user_signed_in? %>

      <li class="nav_item">

        <%= link_to "Users", users_path, class: "nav_link" %>

      </li>




      <li class="nav_item">

        <%= link_to "My Posts", user_posts_path(current_user), class: "nav_link" %>

      </li>




      <li class="nav_item">

        <%= link_to "New Post", new_user_post_path(current_user), class: "nav_link" %>

      </li>




      <li class="nav_split"></li>




      <li class="nav_item">

        <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete, confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: "nav_link" %>

      </li>




      <li class="nav_item"> 

        <%= link_to "Reset Password", edit_user_registration_path, class: "nav_link" %>

      </li>




      <li class="nav_item">

        <%= link_to current_user, class: "nav_profile", title: current_user.name do %>

          <%= image_tag(current_user.photo, alt: current_user.name, onerror: "replaceWithDefaultImage(this, \"/assets/default_user.jpg\")", class: "nav_photo") %>

        <% end %>

      </li>

    <% else %>

      <li class="nav_item">

        <%= link_to "Sign In", new_user_session_path, class: "nav_link" %>

      </li>




      <li class="nav_split"></li>




      <li class="nav_item">

        <%= link_to "Sign Up", new_user_registration_path, class: "nav_link" %>

      </li>

    <% end %>

  </ul>

</nav>

app/views/shared/_popup.erb
<div class="popup">
  <% if notice %>
    <p class="popup_notice"><%= notice %></p>
  <% elsif alert %>
    <p class="popup_alert"><%= alert %></p>
  <% else %>
    <p class="popup_placeholder">&nbsp;</p>
  <% end %>
</div>

app/views/shared/_post_card.html.erb
<div class='<%= post_card_class %>'>
    <h3><%= link_to post.title.capitalize, user_post_path(@users, post), class: 'post_card_title' %></h3>

    <div>
        <p class='post_card_text'>
            <% if post.text.length > 100 %>
                <%= truncate(post.text, length: 100) %>
            <% else %>
                <%= post.text %>
            <% end %>
        </p>

        <div class='post_card_grid'>
            <div class='post_card_actions'>
                <%= render 'shared/button', btnName: 'Add comment', btnPath: new_user_post_comment_path(@users, post), btnClass: 'btn btn_interact' %>
                <%= render 'shared/form', model: @like, url: user_post_likes_path(@users, post), fields: [] %>
            </div>

            <p class='post_card_counters'>Comments: <%= post.comments_counter %> | Likes: <%= post.likes_counter %></p>
        </div>
    </div>
</div>

app/views/shared/_user_card.html.erb
<%= javascript_tag do %>
  function replaceWithDefaultImage(image, default_image_path) {
    image.onerror = "";
    image.src = default_image_path;
    return true;
  }
<% end %>

<%= link_to user, class: user_card_class do %>
  <div class='user_card_photo'>
    <%= image_tag(user.photo, alt: user.name, onerror: "replaceWithDefaultImage(this,'https://picsum.photos/200/300')") %>
  </div>

  <div class=user_card_text>
    <h2><%= user.name%></h2>
    <p>Posts: <%= user.postsCounter%></p>
  </div>
<% end %>

app/views/users/home.html.erb
<%= content_for :title, "Home | " %>

<div class='home'>
  <h1 class='home_title'>Troos Blog<span> by <a href='https://github.com/Kgomotso196/' target='_blank'>Kgomotso196</a></span></h1>
  <p class='home_description'>The Blog app is evolving into a dynamic platform where users can browse posts, engage with content through comments, and express appreciation via likes.</p>
</div>

app/views/users/index.html.erb
<% content_for :title, 'Users | ' %>

<h1 class='title'>Troos Blog</h1>

<ul>
  <% if @users.empty? %>
    <p class="user_empty-message">No users yet!</p>
  <% else %>
    <% @users.each do |user| %>
      <li>
        <%= render 'shared/user_card', user: user, user_card_class: 'user_card' %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= content_for :title, "#{@users.name} | " %>

<div class='user_profile'>
  <div class='user_profile_header'>
    <%= render 'shared/user_card', user: @users, user_card_class: 'user_card no_hover' %>
    <div class='user_profile_bio'>
      <div>
        <h3>Bio</h3>
          <%= render 'shared/button', btnName: 'New post +', btnClass: 'btn btn_cta btn_cta_alt btn_cta_new', btnPath: new_user_post_path(@users) %>
      </div>
      <p><%= @users.bio %></p>
    </div>
  </div>

  <ul class='post_list'>
    <% if @users.most_recent_three_posts.empty? %>
      <p class='user_empty-message'>No posts yet!</p>
    <% else %>
      <% @users.most_recent_three_posts.each do |post| %>
        <li>
          <%= render 'shared/post_card', post: post, post_card_class: 'post_card' %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <% if @users.postsCounter %>
    <div class='post_cta'>
        <%=render 'shared/button', btnName: 'See all posts', btnClass: 'btn btn_cta', btnPath: user_posts_path(@users) %>
    </div>
  <% end %>
</div>